name: Build & Publish Documentation

on:
  push:
    branches:
    - main
    paths:
    - mk.helpers/**
    - docs/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - mk.helpers/**
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build project (generate XML docs)
      run: dotnet build mk.helpers/mk.helpers.csproj --configuration Release

    - name: Generate API metadata
      working-directory: docs
      run: docfx metadata

    - name: Build documentation site
      working-directory: docs
      run: docfx build
      continue-on-error: false

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
